### ISSUE TITLE
Create Book page

### ISSUE THREAD

**Issue by ethangambles** [ainc/hof-gatsby-sanity#8]
Most of this looks like it can be static.

**Comment by LKRamen** [comment]
can you assign me to this

**Comment by ethangambles** [comment]
@LKRamen  Check out [this component](https://github.com/ainc/hof-gatsby-sanity/tree/main/webs/src/components/IconPair) from a new commit that will save you a bit of time.

**Comment by LKRamen** [comment]
Will it automatically align it to be next to the title or will I have to go in and change that?

**Comment by ethangambles** [comment]
Good question - you'd have to change it. This is how I did it: [https://github.com/ainc/hof-gatsby-sanity/blob/da58761ea931b11251fbb084f5f7b6b9e53008cf/webs/src/pages/index.js#L37](https://github.com/ainc/hof-gatsby-sanity/blob/da58761ea931b11251fbb084f5f7b6b9e53008cf/webs/src/pages/index.js#L37)
